import { Component } from '@angular/core';
import { BtnCellRenderer } from './button-cell-renderer.component';
import { TotalValueRenderer } from './simplerender.component';

import {BttnCellRenderer} from './bttn-cell1-renderer.component';
declare let $: any;
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent   {

  private gridApi;
  private gridColumnApi;
 
  private defaultColDef; 
    title = 'Aggriddemo';
  columnDefs =
  [ 
    { 
      headerName:'EDIT',
      field: 'EDIT', 
      cellRenderer: 'bttnCellRenderer', 
      cellRendererParams: {
        clicked: function(field: any) { 
          onRowClicked(field);
        }
      },
      minWidth: 150
    },
    {headerName : 'Error Code' ,field:  'ErrorCode' ,sortable:true,filter:true,editable:true},
    {headerName : 'Vendor Id' ,field:  'VendorId' ,sortable:true,filter:true},
    {headerName : 'Tax Id' ,field:  'TaxId' ,sortable:true,filter:true},
    {headerName : 'Payee' ,field:  'Payee' ,sortable:true,filter:true},
    {headerName : 'Address 1' ,field:  'Address1' ,sortable:true,filter:true},
    {headerName : 'City' ,field:  'City' ,sortable:true,filter:true},
    {headerName : 'State' ,field:  'State' ,sortable:true,filter:true},
    {headerName : 'Zip' ,field:  'Zip' ,sortable:true,filter:true},
    {headerName : 'Payment Type' ,field:  'Payment Type' ,sortable:true,filter:true},
    {headerName : 'Payment Number' ,field:  'Payment Number' ,sortable:true,filter:true},
    {headerName : 'Issue Date' ,field:  'Issue Date' ,sortable:true,filter:true},
    {headerName : 'Received Date' ,field:  'Received Date' ,sortable:true,filter:true},
    {headerName : 'Amount' ,field:  'Amount' ,sortable:true,filter:true},
    {headerName : 'Financial institution Routing Number ' ,field:  'Financial institution Routing Number ' ,sortable:true,filter:true},
    {headerName : 'Account Number' ,field:  'AccountNumber' ,sortable:true,filter:true},
    {headerName : "Status" ,field:  "Status" ,sortable:true,filter:true},
    {headerName : "Platform Type" ,field:  "Platform Type" ,sortable:true,filter:true},
    {headerName : "Last Updated By" ,field:  "Last Updated By" ,sortable:true,filter:true},
    {headerName : "Last Updated Date" ,field:  "Last Updated Date" ,sortable:true,filter:true},
    {headerName : "GL -Company" ,field:  "GL -Company" ,sortable:true,filter:true},
    {headerName : "GL -Facility" ,field:  "GL -Facility" ,sortable:true,filter:true},
    {headerName : "GL -Department" ,field:  "GL -Department" ,sortable:true,filter:true},
    {headerName : "GL -Account" ,field:  "GL -Account" ,sortable:true,filter:true},
    {headerName : "GL -Market" ,field:  "GL -Market" ,sortable:true,filter:true},
    {headerName : "GL -Product" ,field:  "GL -Product" ,sortable:true,filter:true},
    {headerName : "GL -Platform" ,field:  "GL -Platform" ,sortable:true,filter:true},
    {headerName : "GL -Business Segment" ,field:  "GL -Business Segment" ,sortable:true,filter:true},
    {headerName : "GL -HMHS COID" ,field:  "GL -HMHS COID" ,sortable:true,filter:true},
    {headerName : "GL -Non GAAP_Future1" ,field:  "GL -Non GAAP_Future1" ,sortable:true,filter:true}    
];
 
frameworkComponents={ 
    bttnCellRenderer: BttnCellRenderer ,totalvaluerenderer:TotalValueRenderer}
  // [ {field: 'make',sortable:true,filter:true},
  // {field: 'model',sortable:true,filter:true},
  // {field: 'price',sortable:true,filter:true}];
  rowData =
  [
    {
        
        "ErrorCode": "R03",
        "VendorId": "689498",
        "TaxId": "831692886",
        "Payee": "Kris Huenink Counseling Services",
        "Address1": "PO BOX 180680",
        "City": "DELAFIELD",
        "State": "Wisconsin",
        "Zip": "53018",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/24/20",
        "Received Date": "12/31/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "75911988",
        "AccountNumber": "7.5912E+17",
        "Status": "Rejected",
        "Platform Type": "CAS",
        "Last Updated By": "system",
        "Last Updated Date": "12/31/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R03",
        "VendorId": "689498",
        "TaxId": "831692886",
        "Payee": "Kris Huenink Counseling Services",
        "Address1": "PO BOX 180680",
        "City": "DELAFIELD",
        "State": "Wisconsin",
        "Zip": "53018",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/24/20",
        "Received Date": "12/31/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "75911988",
        "AccountNumber": "7.5912E+17",
        "Status": "Rejected",
        "Platform Type": "MTV",
        "Last Updated By": "system",
        "Last Updated Date": "12/31/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R02",
        "VendorId": "450199",
        "TaxId": "28380480",
        "Payee": "M L BLOUNT LCSW",
        "Address1": "8909 Regents Park Dr Ste 420",
        "City": "TAMPA",
        "State": "Florida",
        "Zip": "33647",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/24/20",
        "Received Date": "12/31/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "63102152",
        "AccountNumber": "1.00008E+12",
        "Status": "Rejected",
        "Platform Type": "CAS",
        "Last Updated By": "system",
        "Last Updated Date": "12/31/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R02",
        "VendorId": "450200",
        "TaxId": "28380480",
        "Payee": "M L BLOUNT LCSW",
        "Address1": "7209 HAMMET RD",
        "City": "TAMPA",
        "State": "Florida",
        "Zip": "33647",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/24/20",
        "Received Date": "12/31/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "63102152",
        "AccountNumber": "1.00008E+12",
        "Status": "Rejected",
        "Platform Type": "CAS",
        "Last Updated By": "system",
        "Last Updated Date": "12/31/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R02",
        "VendorId": "450199",
        "TaxId": "28380480",
        "Payee": "M L BLOUNT LCSW",
        "Address1": "8909 Regents Park Dr Ste 420",
        "City": "TAMPA",
        "State": "Florida",
        "Zip": "33647",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/24/20",
        "Received Date": "12/31/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "63102152",
        "AccountNumber": "1.00008E+12",
        "Status": "Rejected",
        "Platform Type": "MTV",
        "Last Updated By": "system",
        "Last Updated Date": "12/31/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R02",
        "VendorId": "450200",
        "TaxId": "28380480",
        "Payee": "M L BLOUNT LCSW",
        "Address1": "7209 HAMMET RD",
        "City": "TAMPA",
        "State": "Florida",
        "Zip": "33647",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/24/20",
        "Received Date": "12/31/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "63102152",
        "AccountNumber": "1.00008E+12",
        "Status": "Rejected",
        "Platform Type": "MTV",
        "Last Updated By": "system",
        "Last Updated Date": "12/31/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R04",
        "VendorId": "688626",
        "TaxId": "880511493",
        "Payee": "Reno Diagnostic Centers",
        "Address1": "PO BOX 22995",
        "City": "PASADENA",
        "State": "California",
        "Zip": "91185",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/28/20",
        "Received Date": "12/31/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "121100782",
        "AccountNumber": "121100782",
        "Status": "Rejected",
        "Platform Type": "CAS",
        "Last Updated By": "system",
        "Last Updated Date": "12/31/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R04",
        "VendorId": "688626",
        "TaxId": "880511493",
        "Payee": "Reno Diagnostic Centers",
        "Address1": "PO BOX 22995",
        "City": "PASADENA",
        "State": "California",
        "Zip": "91185",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/28/20",
        "Received Date": "12/31/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "121100782",
        "AccountNumber": "121100782",
        "Status": "Rejected",
        "Platform Type": "MTV",
        "Last Updated By": "system",
        "Last Updated Date": "12/31/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R03",
        "VendorId": "694452",
        "TaxId": "362563033",
        "Payee": "SUSAN G LEAVENWORTH PHD",
        "Address1": "4500 BOWLING BLVD STE 100",
        "City": "LOUISVILLE",
        "State": "Kentucky",
        "Zip": "40207",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/24/20",
        "Received Date": "12/31/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "83002342",
        "AccountNumber": "7146496090",
        "Status": "Rejected",
        "Platform Type": "CAS",
        "Last Updated By": "system",
        "Last Updated Date": "12/31/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R03",
        "VendorId": "694452",
        "TaxId": "362563033",
        "Payee": "SUSAN G LEAVENWORTH PHD",
        "Address1": "4500 BOWLING BLVD STE 100",
        "City": "LOUISVILLE",
        "State": "Kentucky",
        "Zip": "40207",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/24/20",
        "Received Date": "12/31/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "83002342",
        "AccountNumber": "7146496090",
        "Status": "Rejected",
        "Platform Type": "MTV",
        "Last Updated By": "system",
        "Last Updated Date": "12/31/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R04",
        "VendorId": "701625",
        "TaxId": "851463123",
        "Payee": "VITAL WELLNESS CLINIC LLC",
        "Address1": "4001 COMMERICAL CENTER DR STE 1",
        "City": "MARION",
        "State": "Arkansas",
        "Zip": "72364",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/23/20",
        "Received Date": "12/30/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "84001148",
        "AccountNumber": "27454",
        "Status": "Rejected",
        "Platform Type": "CAS",
        "Last Updated By": "system",
        "Last Updated Date": "12/30/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R04",
        "VendorId": "701625",
        "TaxId": "851463123",
        "Payee": "VITAL WELLNESS CLINIC LLC",
        "Address1": "4001 COMMERICAL CENTER DR STE 1",
        "City": "MARION",
        "State": "Arkansas",
        "Zip": "72364",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/23/20",
        "Received Date": "12/30/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "84001148",
        "AccountNumber": "27454",
        "Status": "Rejected",
        "Platform Type": "MTV",
        "Last Updated By": "system",
        "Last Updated Date": "12/30/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R03",
        "VendorId": "689204",
        "TaxId": "260861245",
        "Payee": "IRINA FELDMAN MD INC",
        "Address1": "329 S MOORPARK RD",
        "City": "THOUSAND OAKS",
        "State": "California",
        "Zip": "91361",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/23/20",
        "Received Date": "12/29/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "322271724",
        "AccountNumber": "151071575",
        "Status": "Rejected",
        "Platform Type": "CAS",
        "Last Updated By": "system",
        "Last Updated Date": "12/29/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R03",
        "VendorId": "689204",
        "TaxId": "260861245",
        "Payee": "IRINA FELDMAN MD INC",
        "Address1": "329 S MOORPARK RD",
        "City": "THOUSAND OAKS",
        "State": "California",
        "Zip": "91361",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/23/20",
        "Received Date": "12/29/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "322271724",
        "AccountNumber": "151071575",
        "Status": "Rejected",
        "Platform Type": "MTV",
        "Last Updated By": "system",
        "Last Updated Date": "12/29/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R04",
        "VendorId": "688625",
        "TaxId": "880511493",
        "Payee": "THADDEUS A LAIRD MD",
        "Address1": "PO BOX 60000",
        "City": "LOS ANGELES",
        "State": "California",
        "Zip": "90060",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/23/20",
        "Received Date": "12/29/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "121100782",
        "AccountNumber": "121100782",
        "Status": "Rejected",
        "Platform Type": "CAS",
        "Last Updated By": "system",
        "Last Updated Date": "12/29/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R04",
        "VendorId": "688625",
        "TaxId": "880511493",
        "Payee": "THADDEUS A LAIRD MD",
        "Address1": "PO BOX 60000",
        "City": "LOS ANGELES",
        "State": "California",
        "Zip": "90060",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/23/20",
        "Received Date": "12/29/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "121100782",
        "AccountNumber": "121100782",
        "Status": "Rejected",
        "Platform Type": "MTV",
        "Last Updated By": "system",
        "Last Updated Date": "12/29/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R03",
        "VendorId": "618082",
        "TaxId": "233001904",
        "Payee": "DOCTORS HOSPITAL OF LAREDO",
        "Address1": "PO BOX 844166",
        "City": "DALLAS",
        "State": "Texas",
        "Zip": "75284",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/21/20",
        "Received Date": "12/25/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "71000039",
        "AccountNumber": "81880503047",
        "Status": "Rejected",
        "Platform Type": "CAS",
        "Last Updated By": "system",
        "Last Updated Date": "12/25/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R03",
        "VendorId": "618083",
        "TaxId": "233001904",
        "Payee": "DOCTORS HOSPITAL OF LAREDO",
        "Address1": "PO BOX 844166",
        "City": "DALLAS",
        "State": "Texas",
        "Zip": "75284",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/21/20",
        "Received Date": "12/25/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "71000039",
        "AccountNumber": "81880503047",
        "Status": "Rejected",
        "Platform Type": "CAS",
        "Last Updated By": "system",
        "Last Updated Date": "12/25/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R03",
        "VendorId": "618082",
        "TaxId": "233001904",
        "Payee": "DOCTORS HOSPITAL OF LAREDO",
        "Address1": "PO BOX 844166",
        "City": "DALLAS",
        "State": "Texas",
        "Zip": "75284",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/21/20",
        "Received Date": "12/25/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "71000039",
        "AccountNumber": "81880503047",
        "Status": "Rejected",
        "Platform Type": "MTV",
        "Last Updated By": "system",
        "Last Updated Date": "12/25/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R03",
        "VendorId": "618083",
        "TaxId": "233001904",
        "Payee": "DOCTORS HOSPITAL OF LAREDO",
        "Address1": "PO BOX 844166",
        "City": "DALLAS",
        "State": "Texas",
        "Zip": "75284",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/21/20",
        "Received Date": "12/25/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "71000039",
        "AccountNumber": "81880503047",
        "Status": "Rejected",
        "Platform Type": "MTV",
        "Last Updated By": "system",
        "Last Updated Date": "12/25/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R03",
        "VendorId": "699191",
        "TaxId": "208489105",
        "Payee": "HACKENSACK UMC MOUNTAINSIDE",
        "Address1": "PO BOX 417618",
        "City": "BOSTON",
        "State": "Massachusetts",
        "Zip": "2241",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/21/20",
        "Received Date": "12/25/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "111000025",
        "AccountNumber": "4.8838E+12",
        "Status": "Rejected",
        "Platform Type": "CAS",
        "Last Updated By": "system",
        "Last Updated Date": "12/25/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R03",
        "VendorId": "699191",
        "TaxId": "208489105",
        "Payee": "HACKENSACK UMC MOUNTAINSIDE",
        "Address1": "PO BOX 417618",
        "City": "BOSTON",
        "State": "Massachusetts",
        "Zip": "2241",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/21/20",
        "Received Date": "12/25/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "111000025",
        "AccountNumber": "4.8838E+12",
        "Status": "Rejected",
        "Platform Type": "MTV",
        "Last Updated By": "system",
        "Last Updated Date": "12/25/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R03",
        "VendorId": "684965",
        "TaxId": "821857532",
        "Payee": "Hawk Medical Consulting DBA Heli",
        "Address1": "927 NW 130th Ter",
        "City": "Sunrise",
        "State": "Florida",
        "Zip": "33325",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/21/20",
        "Received Date": "12/25/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "123000848",
        "AccountNumber": "8.9883E+11",
        "Status": "Rejected",
        "Platform Type": "CAS",
        "Last Updated By": "system",
        "Last Updated Date": "12/25/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R03",
        "VendorId": "684965",
        "TaxId": "821857532",
        "Payee": "Hawk Medical Consulting DBA Heli",
        "Address1": "927 NW 130th Ter",
        "City": "Sunrise",
        "State": "Florida",
        "Zip": "33325",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/21/20",
        "Received Date": "12/25/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "123000848",
        "AccountNumber": "8.9883E+11",
        "Status": "Rejected",
        "Platform Type": "MTV",
        "Last Updated By": "system",
        "Last Updated Date": "12/25/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R03",
        "VendorId": "618081",
        "TaxId": "233001904",
        "Payee": "Laredo Regional Medical Center L",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/21/20",
        "Received Date": "12/25/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "71000039",
        "AccountNumber": "81880503047",
        "Status": "Rejected",
        "Platform Type": "CAS",
        "Last Updated By": "system",
        "Last Updated Date": "12/25/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R03",
        "VendorId": "618081",
        "TaxId": "233001904",
        "Payee": "Laredo Regional Medical Center L",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/21/20",
        "Received Date": "12/25/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "71000039",
        "AccountNumber": "81880503047",
        "Status": "Rejected",
        "Platform Type": "MTV",
        "Last Updated By": "system",
        "Last Updated Date": "12/25/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R03",
        "VendorId": "697122",
        "TaxId": "61047696",
        "Payee": "MALETTA PFEIFFER ASSOCIATES",
        "Address1": "30 PECK RD",
        "City": "Torrington",
        "State": "Connecticut",
        "Zip": "6790",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/21/20",
        "Received Date": "12/25/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "211174275",
        "AccountNumber": "730067988",
        "Status": "Rejected",
        "Platform Type": "CAS",
        "Last Updated By": "system",
        "Last Updated Date": "12/25/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R03",
        "VendorId": "697123",
        "TaxId": "61047696",
        "Payee": "MALETTA PFEIFFER ASSOCIATES",
        "Address1": "30 PECK RD",
        "City": "TORRINGTON",
        "State": "Connecticut",
        "Zip": "6790",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/21/20",
        "Received Date": "12/25/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "211174275",
        "AccountNumber": "730067988",
        "Status": "Rejected",
        "Platform Type": "CAS",
        "Last Updated By": "system",
        "Last Updated Date": "12/25/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R03",
        "VendorId": "697122",
        "TaxId": "61047696",
        "Payee": "MALETTA PFEIFFER ASSOCIATES",
        "Address1": "30 PECK RD",
        "City": "Torrington",
        "State": "Connecticut",
        "Zip": "6790",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/21/20",
        "Received Date": "12/25/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "211174275",
        "AccountNumber": "730067988",
        "Status": "Rejected",
        "Platform Type": "MTV",
        "Last Updated By": "system",
        "Last Updated Date": "12/25/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R03",
        "VendorId": "697123",
        "TaxId": "61047696",
        "Payee": "MALETTA PFEIFFER ASSOCIATES",
        "Address1": "30 PECK RD",
        "City": "TORRINGTON",
        "State": "Connecticut",
        "Zip": "6790",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/21/20",
        "Received Date": "12/25/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "211174275",
        "AccountNumber": "730067988",
        "Status": "Rejected",
        "Platform Type": "MTV",
        "Last Updated By": "system",
        "Last Updated Date": "12/25/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R03",
        "VendorId": "697121",
        "TaxId": "61047696",
        "Payee": "MALETTA PFEIFFER AND ASSOCIATE",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/21/20",
        "Received Date": "12/25/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "211174275",
        "AccountNumber": "730067988",
        "Status": "Rejected",
        "Platform Type": "CAS",
        "Last Updated By": "system",
        "Last Updated Date": "12/25/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R03",
        "VendorId": "697121",
        "TaxId": "61047696",
        "Payee": "MALETTA PFEIFFER AND ASSOCIATE",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/21/20",
        "Received Date": "12/25/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "211174275",
        "AccountNumber": "730067988",
        "Status": "Rejected",
        "Platform Type": "MTV",
        "Last Updated By": "system",
        "Last Updated Date": "12/25/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R03",
        "VendorId": "699225",
        "TaxId": "834343219",
        "Payee": "MONT BELVIEU MD URGENT CARE",
        "Address1": "9205 EAGLE DR STE 200",
        "City": "MONT BELVIEU",
        "State": "Texas",
        "Zip": "77523",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/21/20",
        "Received Date": "12/25/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "111000614",
        "AccountNumber": "3.9935E+12",
        "Status": "Rejected",
        "Platform Type": "CAS",
        "Last Updated By": "system",
        "Last Updated Date": "12/25/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R03",
        "VendorId": "699226",
        "TaxId": "834343219",
        "Payee": "Mont Belvieu MD Urgent Care",
        "Address1": "9205 Eagle Dr Ste 200",
        "City": "Mont Belvieu",
        "State": "Texas",
        "Zip": "77523",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/21/20",
        "Received Date": "12/25/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "111000614",
        "AccountNumber": "3.9935E+12",
        "Status": "Rejected",
        "Platform Type": "CAS",
        "Last Updated By": "system",
        "Last Updated Date": "12/25/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R03",
        "VendorId": "699227",
        "TaxId": "834343219",
        "Payee": "MONT BELVIEU MD URGENT CARE",
        "Address1": "9205 EAGLE DR STE 200",
        "City": "MONT BELVIEU",
        "State": "Texas",
        "Zip": "77523",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/21/20",
        "Received Date": "12/25/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "111000614",
        "AccountNumber": "3.9935E+12",
        "Status": "Rejected",
        "Platform Type": "CAS",
        "Last Updated By": "system",
        "Last Updated Date": "12/25/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R03",
        "VendorId": "699225",
        "TaxId": "834343219",
        "Payee": "MONT BELVIEU MD URGENT CARE",
        "Address1": "9205 EAGLE DR STE 200",
        "City": "MONT BELVIEU",
        "State": "Texas",
        "Zip": "77523",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/21/20",
        "Received Date": "12/25/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "111000614",
        "AccountNumber": "3.9935E+12",
        "Status": "Rejected",
        "Platform Type": "MTV",
        "Last Updated By": "system",
        "Last Updated Date": "12/25/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R03",
        "VendorId": "699226",
        "TaxId": "834343219",
        "Payee": "Mont Belvieu MD Urgent Care",
        "Address1": "9205 Eagle Dr Ste 200",
        "City": "Mont Belvieu",
        "State": "Texas",
        "Zip": "77523",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/21/20",
        "Received Date": "12/25/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "111000614",
        "AccountNumber": "3.9935E+12",
        "Status": "Rejected",
        "Platform Type": "MTV",
        "Last Updated By": "system",
        "Last Updated Date": "12/25/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R03",
        "VendorId": "699227",
        "TaxId": "834343219",
        "Payee": "MONT BELVIEU MD URGENT CARE",
        "Address1": "9205 EAGLE DR STE 200",
        "City": "MONT BELVIEU",
        "State": "Texas",
        "Zip": "77523",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/21/20",
        "Received Date": "12/25/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "111000614",
        "AccountNumber": "3.9935E+12",
        "Status": "Rejected",
        "Platform Type": "MTV",
        "Last Updated By": "system",
        "Last Updated Date": "12/25/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R03",
        "VendorId": "685687",
        "TaxId": "260351040",
        "Payee": "Nicholas Angelopoulos DO SC",
        "Address1": "PO Box 175",
        "City": "Tinley Park",
        "State": "Illinois",
        "Zip": "60477",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/21/20",
        "Received Date": "12/25/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "71000013",
        "AccountNumber": "38052119",
        "Status": "Rejected",
        "Platform Type": "CAS",
        "Last Updated By": "system",
        "Last Updated Date": "12/25/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R03",
        "VendorId": "685687",
        "TaxId": "260351040",
        "Payee": "Nicholas Angelopoulos DO SC",
        "Address1": "PO Box 175",
        "City": "Tinley Park",
        "State": "Illinois",
        "Zip": "60477",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/21/20",
        "Received Date": "12/25/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "71000013",
        "AccountNumber": "38052119",
        "Status": "Rejected",
        "Platform Type": "MTV",
        "Last Updated By": "system",
        "Last Updated Date": "12/25/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R03",
        "VendorId": "701587",
        "TaxId": "522376439",
        "Payee": "THERAPY SOLUTIONS",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/22/20",
        "Received Date": "12/25/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "111302587",
        "AccountNumber": "8.1827E+11",
        "Status": "Rejected",
        "Platform Type": "CAS",
        "Last Updated By": "system",
        "Last Updated Date": "12/25/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R03",
        "VendorId": "701587",
        "TaxId": "522376439",
        "Payee": "THERAPY SOLUTIONS",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/22/20",
        "Received Date": "12/25/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "111302587",
        "AccountNumber": "8.1827E+11",
        "Status": "Rejected",
        "Platform Type": "MTV",
        "Last Updated By": "system",
        "Last Updated Date": "12/25/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R03",
        "VendorId": "689656",
        "TaxId": "821512732",
        "Payee": "APEX HOME HEALTH SOUTH",
        "Address1": "75 Dominican Rd Ste 209",
        "City": "La Place",
        "State": "Louisiana",
        "Zip": "70068",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/17/20",
        "Received Date": "12/23/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "65000090",
        "AccountNumber": "2046",
        "Status": "Rejected",
        "Platform Type": "CAS",
        "Last Updated By": "system",
        "Last Updated Date": "12/23/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R03",
        "VendorId": "689656",
        "TaxId": "821512732",
        "Payee": "APEX HOME HEALTH SOUTH",
        "Address1": "75 Dominican Rd Ste 209",
        "City": "La Place",
        "State": "Louisiana",
        "Zip": "70068",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/17/20",
        "Received Date": "12/23/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "65000090",
        "AccountNumber": "2046",
        "Status": "Rejected",
        "Platform Type": "MTV",
        "Last Updated By": "system",
        "Last Updated Date": "12/23/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R02",
        "VendorId": "684703",
        "TaxId": "834644378",
        "Payee": "Kathryn Vaughn",
        "Address1": "3160 Main St Ste 102",
        "City": "Duluth",
        "State": "Georgia",
        "Zip": "30096",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/17/20",
        "Received Date": "12/23/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "265270413",
        "AccountNumber": "265270413",
        "Status": "Rejected",
        "Platform Type": "CAS",
        "Last Updated By": "system",
        "Last Updated Date": "12/23/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R02",
        "VendorId": "684703",
        "TaxId": "834644378",
        "Payee": "Kathryn Vaughn",
        "Address1": "3160 Main St Ste 102",
        "City": "Duluth",
        "State": "Georgia",
        "Zip": "30096",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/17/20",
        "Received Date": "12/23/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "265270413",
        "AccountNumber": "265270413",
        "Status": "Rejected",
        "Platform Type": "MTV",
        "Last Updated By": "system",
        "Last Updated Date": "12/23/20",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R13",
        "VendorId": "696604",
        "TaxId": "202600100",
        "Payee": "ENT FOR CHILDREN PA",
        "Address1": "783 N DENTON TAP RD STE 200",
        "City": "Coppell",
        "State": "Texas",
        "Zip": "75019",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/18/20",
        "Received Date": "12/22/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "111024548",
        "AccountNumber": "2011682",
        "Status": "Rejected",
        "Platform Type": "CAS",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R13",
        "VendorId": "696604",
        "TaxId": "202600100",
        "Payee": "ENT FOR CHILDREN PA",
        "Address1": "783 N DENTON TAP RD STE 200",
        "City": "Coppell",
        "State": "Texas",
        "Zip": "75019",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/18/20",
        "Received Date": "12/22/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "111024548",
        "AccountNumber": "2011682",
        "Status": "Rejected",
        "Platform Type": "MTV",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R13",
        "VendorId": "696605",
        "TaxId": "202600100",
        "Payee": "PAUL W BAUER MD",
        "Address1": "783 N DENTON TAP RD STE 200",
        "City": "COPPELL",
        "State": "Texas",
        "Zip": "75019",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/18/20",
        "Received Date": "12/22/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "111024548",
        "AccountNumber": "2011682",
        "Status": "Rejected",
        "Platform Type": "CAS",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    },
    {
        
        "ErrorCode": "R13",
        "VendorId": "696605",
        "TaxId": "202600100",
        "Payee": "PAUL W BAUER MD",
        "Address1": "783 N DENTON TAP RD STE 200",
        "City": "COPPELL",
        "State": "Texas",
        "Zip": "75019",
        "Payment Type": "ACH",
        "Payment Number": "1.435E+12",
        "Issue Date": "12/18/20",
        "Received Date": "12/22/20",
        "Amount": "$0.01 ",
        "Financial institution Routing Number": "111024548",
        "AccountNumber": "2011682",
        "Status": "Rejected",
        "Platform Type": "MTV",
        "GL -Company": "4",
        "GL -Facility": "1001",
        "GL -Department": "0",
        "GL -Account": "0",
        "GL -Market": "0",
        "GL -Product": "0",
        "GL -Platform": "0",
        "GL -Business Segment": "0",
        "GL -HMHS COID": "0",
        "GL -Non GAAP_Future1": "0"
    }
];
onRowClicked(event: any) { console.log('row',event);
$("#anumber").text(event.data.AccountNumber);
$("#add").text(event.data.Address1);
$("#amt").text(event.data.Amount);
$("#city").text(event.data.City);
$("#err").text(event.data.ErrorCode);
 


$("#imagemodal").modal("show");}
  // [
  //   {make: 'Toyota',module:'Celica',price :3500},
  //   {make: 'Ford',module:'Mendeo',price :3200},
  //   {make: 'Porsche',module:'Boxter',price :72000}
  //   ];
 

    
}
function onRowClicked(field: any) {
  $("#imagemodal").modal("show");
}

